Select * from customer

--1. What is total revenue generated by male vs female customers?
Select
gender,
sum(purchase_amount)
From customer
Group By 1


--2. Which customer used a discount but still spent more than the average purchase amount?
Select 
customer_id, purchase_amount
From customer
Where discount_applied='Yes' and purchase_amount>= (Select avg(purchase_amount) from customer)



--3 Which are top 5 products with highest average review rating
Select
item_purchased,
round(avg(review_rating::numeric),2) as average_product_rating
From customer
Group By 1
Order By 2 desc
Limit 5



--4. Compare avergae purchase amounts between standard and express shipping.
Select
shipping_type,
round(avg(purchase_amount),2)
From customer
where shipping_type in('Express','Standard')
Group By 1


--5. Do subscribed customers spend more? Compare average spend and total revenue
--between subscribers and non-subscribers.
Select
subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
From customer
group by 1
Order By 4,3 desc


--6. Which 5 products have highest percentage of purchases with discounts applied?
Select
item_purchased,
round(100*sum(case when discount_applied= 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
From customer
Group By 1
order By 2 desc
Limit 5



--7. Segment customers into new,returning, and loyal based on their total
--number of previous purchases, and show count of each segment
With customer_type as(
Select
customer_id,
previous_purchases,
case 
	when previous_purchases=1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal' 
 	end as customer_segment
From customer
)
Select 
customer_segment,
count(*) as number_of_customers
From customer_type
gROUP bY 1


--8. What are top 3 most purchases products from each category?
With t1 as(
Select
category,
item_purchased,
count(customer_id) as total_orders,
row_number()over(Partition by category Order By count(item_purchased) Desc) rnk
From customer
Group By 1,2
)
Select
category,
item_purchased,
total_orders
From t1
Where rnk<4



--9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
Select
subscription_status,
count(customer_id) as repeat_buyers
From customer
Where previous_purchases>5
group by 1 



--10. What is revenue contribution of each age group?
Select
age_group,
sum(purchase_amount) as total_revenue
From customer
Group By 1
Order By 2 DESC
